# Dependabot configuration for JFLAP-NG
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    # Group all GitHub Actions updates together
    groups:
      github-actions:
        patterns:
          - "*"

  # Maintain dependencies for Gradle (including wrapper)
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    # Separate groups for different types of dependencies
    groups:
      # Group for project dependencies
      gradle-dependencies:
        patterns:
          - "org.apache.xmlgraphics:*"
          - "junit:*"
      # Group for Gradle wrapper
      gradle-wrapper:
        patterns:
          - "gradle"
    # Allow up to 10 open pull requests for dependencies
    open-pull-requests-limit: 10
    # Ignore major version updates for now
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

